/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlytrongxe;

/**
 *
 * @author Nguyen Nghia
 */
public class MenuQuanTri extends javax.swing.JFrame {

    /**
     * Creates new form MenuQuanTri
     */
    public MenuQuanTri() {
        initComponents();
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Quanlynhanvienbtn = new javax.swing.JButton();
        QuanlykhachhangBtn = new javax.swing.JButton();
        BanveBtn = new javax.swing.JButton();
        TrucBtn = new javax.swing.JButton();
        DoanhthuBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ TRÔNG XE ĐẠI HỌC CÔNG NGHIỆP HÀ NỘI ");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Quanlynhanvienbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Quanlynhanvienbtn.setText("Quản lý nhân viên");
        Quanlynhanvienbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Quanlynhanvienbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanlynhanvienbtnActionPerformed(evt);
            }
        });

        QuanlykhachhangBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        QuanlykhachhangBtn.setText("Quản lý khách hàng");
        QuanlykhachhangBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        QuanlykhachhangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanlykhachhangBtnActionPerformed(evt);
            }
        });

        BanveBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BanveBtn.setText("Bán vé");
        BanveBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BanveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanveBtnActionPerformed(evt);
            }
        });

        TrucBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TrucBtn.setText("Quản lý trực");
        TrucBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TrucBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrucBtnActionPerformed(evt);
            }
        });

        DoanhthuBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DoanhthuBtn.setText("Doanh thu");
        DoanhthuBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DoanhthuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoanhthuBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Chức năng");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DoanhthuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TrucBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BanveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(QuanlykhachhangBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Quanlynhanvienbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(68, 68, 68))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BanveBtn, DoanhthuBtn, QuanlykhachhangBtn, Quanlynhanvienbtn, TrucBtn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(Quanlynhanvienbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(QuanlykhachhangBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BanveBtn)
                .addGap(18, 18, 18)
                .addComponent(TrucBtn)
                .addGap(18, 18, 18)
                .addComponent(DoanhthuBtn)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BanveBtn, DoanhthuBtn, QuanlykhachhangBtn, Quanlynhanvienbtn, TrucBtn});

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/anh.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel3)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuanlynhanvienbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanlynhanvienbtnActionPerformed
        // TODO add your handling code here:
        Quanlynhanvien qlnv = new Quanlynhanvien();
        qlnv.setVisible(true);
        dispose();
    }//GEN-LAST:event_QuanlynhanvienbtnActionPerformed

    private void QuanlykhachhangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanlykhachhangBtnActionPerformed
        // TODO add your handling code here:
        Quanlykhachhang qlkh=new Quanlykhachhang();
        qlkh.setVisible(true);
        dispose();
    }//GEN-LAST:event_QuanlykhachhangBtnActionPerformed

    private void BanveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanveBtnActionPerformed
        // TODO add your handling code here:
        Banve bv=new Banve();
        bv.setVisible(true);
        dispose();
    }//GEN-LAST:event_BanveBtnActionPerformed

    private void TrucBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrucBtnActionPerformed
        // TODO add your handling code here:
        Quanlytruc truc=new Quanlytruc();
        truc.setVisible(true);
        dispose();
    }//GEN-LAST:event_TrucBtnActionPerformed

    private void DoanhthuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoanhthuBtnActionPerformed
        // TODO add your handling code here:
        Doanhthu dt=new Doanhthu();
        dt.setVisible(true);
        dispose();
    }//GEN-LAST:event_DoanhthuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuQuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuQuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuQuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuQuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuQuanTri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BanveBtn;
    private javax.swing.JButton DoanhthuBtn;
    private javax.swing.JButton QuanlykhachhangBtn;
    private javax.swing.JButton Quanlynhanvienbtn;
    private javax.swing.JButton TrucBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
